### ISSUE TITLE
on-close event emits initial value when enableTime and noCalendar config props are set to true but does not update v-model

### ISSUE THREAD

**Issue by maga18** [ankurk91/vue-flatpickr-component#109]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```
Thank you for the lovely component.
**Tell about your platform**
* flatPickr version : 4.5.2
* Vue.js version : 2.5.17
* Browser name and version : Chrome
* This package version : 8.0.0

**Current behavior**
I have implemented the vue flatpickr to select time alone without date calendar(noCalendar property set to true). When the input is clicked to select time, on-close event emits the first value(12.00pm) which appears on the input control but does not update the v-model(date).
```js
       enableTime: true,
       noCalendar: true,
       dateFormat: "h:i K",
       defaultDate: null,
       minuteIncrement: "1",
       time_24hr: true
```
**Expected behavior**
on-close event should not display the initial value on the input control, or v-model needs to be updated with the initial value emitted by the on-close event.

It works fine with 4.5.0 version of flatpickr. 

I have tried to reproduce the same on the codepen.
https://codepen.io/maga18/pen/BOemMw

**Comment by ankurk91** [comment]
This is an issue with [flatpickr](https://github.com/flatpickr/flatpickr) itself.
I was able to re-produce the issue with plain js version

https://jsfiddle.net/ug1ehL85/

**Comment by ankurk91** [comment]
The original problem statement was -
The flatpicker should not update DOM without emitting `change` event.

### How to produce this issue -
* Open up my fiddle https://jsfiddle.net/ug1ehL85/
* Open your dev tools console
* Click on input field (dont select any time yet)
* You will notice the input value get updated with `12:00 PM`
* Click outside without selecting any time, you will see `close` event.

### What is the expected behaviour from flatpickr
* It should not update DOM unless user select a date
* If if ever updates DOM, it should emit `change` or `input` event

The vue component relies on `input` event emitted by flatpickr.
`input` and `change` events are almost same in terms of flatpickr.

Feel free to discuss more.

**Comment by kamilwylegala** [comment]
@maga-soma @mintcs Does this issue occur on Firefox browser only?

Did you check it on Chrome? It looks fix in flatpickr is ready, it's a matter of releasing it: https://github.com/flatpickr/flatpickr/pull/1879

**Comment by maga-soma** [comment]
@kamilwylegala, I initially raised this issue occurring in chrome browser
