### ISSUE TITLE
Readonly input gets cleared by pressing backspace key

### ISSUE THREAD

**Issue by kanteankit** [ankurk91/vue-flatpickr-component#113]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.5.16
* Browser name and version : Chrome 68.0.3440.106
* This package version : 8.0.0

**Current behavior**

See the demo link: https://jsfiddle.net/ankurk91/63kzdwLx/
Even though the input has `readonly` attribute, it is still possible to clear the text. This can be done by:
1) double clicking on the input which will select the entire date string
2) Press `backspace` key. The selected text gets cleared.

**Expected behavior**

If you see normal `readonly` inputs, it is not possible to clear their values by pressing backspace.

**Comment by ankurk91** [comment]
The backspace behaviour is by design.
User click on the input field, datepicker pops up, user select a date, user can press backspace (while datepicker opened) and it will clear the input.

I could not reproduce the double click behaviour, if i click on input twice,it brings the datepickr UI. Can you write steps?

**Comment by ankurk91** [comment]
> If you see normal readonly inputs, it is not possible to clear their values by pressing backspace.

Javascript can do anything my friend.
