### ISSUE TITLE
Time not being returned even when "enableTime" is set to true in config.

### ISSUE THREAD

**Issue by abhishek6262** [ankurk91/vue-flatpickr-component#17]
* Vue flatPickr version : 2.4.1
* Vue.js version : 2.1.10
* Browser name and version : Chrome

**Current behavior**

On using v-model only a date is returned even when the "enableTime" has been set to true in the config though the selection of time input field gets enabled.

**Expected behavior**

Either an object or a string should be returned containing the details about the Date and Time selected.

**Comment by ankurk91** [comment]
Can you share your full config object ?

**Comment by ankurk91** [comment]
In order to get only time; use this config:
```js
{
        enableTime: true,
        enableSeconds: true,
        noCalendar: true          
 },
```
This will return values like `11:25:10` 
It means when you set `enableTime:true` it will ask you date and time both.
But if you want to ask only time the you need to disable calendar by `noCalendar: true`.

 You can find the time only example here -
https://github.com/ankurk91/vue-flatpickr-component/blob/master/examples/App.vue#L218-L222

You can also read about all options available here -
https://chmln.github.io/flatpickr/options/
