### ISSUE TITLE
How to display a overlay when disabled?

### ISSUE THREAD

**Issue by ricky11** [ankurk91/vue-flatpickr-component#243]
I sent this request in the original github repo, with no response, so thought to ask here, since i am using the vue component version.

https://github.com/flatpickr/flatpickr/issues/2566

copy/paste :

When I set the config to enable : [] which will cause all dates to be disabled, i would also like to display a overlay on the disabled calendar dates that show some text as to why the dates are disabled?

is there a built in api for this, or do i have to do it in css, can you advise the class name?

I am using vue.

Thanks

**Comment by ankurk91** [comment]
You did not receive any response on original reported issue because you question is too vague .

This package (vue-loading-overlay) is no where related to showing overlay on dates in flatpickr.
The flatpickr itself does not allow to show text on individual dates,

Don't connect your issue with vue, it is a CSS+JS problem.

You are asking for class names so that you can show the text on dates (reason why it is disabled). 
You could use dev tools to inspect the DOM.

Looks like you are a beginner in web development.
I would suggest to describe your issue on stackoverflow, Github is not the best place to ask for such kind of help.
